# Site settings
title: Nymfäldreboendet
email: evelin.foxell+Nymfaldreboendet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Detta är en hemsida för mitt lilla "Nymfäldreboende" 
  där jag kan dels blogga om vad som händer samt lägga 
  upp information och råd.
baseurl: "" # the subpath of your site, e.g. /blog
author: Evelin Foxell
url: "http://nymfaldreboendet.evelinfoxell.se" # the base hostname & protocol for your site
github_username: EvelinFoxell
image: /img/welcome.png
lang: sv_SE
include: ['_pages']
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown